name: custom_soundboard_app
description: A simple cross-platform custom soundboard app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
